server:
  port: 8080 # Dòng khai báo trên Fe

jwt:
  secret: ${JWT_SECRET}
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Auth-service
        - id: auth-service-route
          uri: http://auth-service:8080 # theo port Docker
          predicates:
            - Path=/api/auth/**  # Có thể điều chỉnh theo hướng nhiều phiên bản

        # Menu-service
        - id: menu-service-route
          uri: http://menu-service:8080
          predicates:
            - Path=/api/menu-items/**,/api/menu-item-images/**,/api/categories/**

        # Order-service
        - id: order-service-route
          uri: http://order-service:8080
          predicates:
            - Path=/api/orders/**